apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::145023113164:role/default-eks-node-group-20250613000007393300000002
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::145023113164:user/eks-user
      username: eks-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-13T00:12:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1374"
  uid: 398c92c6-6779-41dd-b8ed-4e042ce2a0c6
